Repository bamin0422/GanDan, pull requests merged in 2020-11, with the labels that each got.

#17 Add RecyclerView to home_fragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/MainActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/adapter/HorizonAdapter.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/crawler/WebCrawler.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/fragment/home_fragment.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/fragment/search_fragment.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/model/Item.kt
  app/src/main/res/layout/home_fragment.xml
  app/src/main/res/layout/recycler_items.xml
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#19 Add DesignTool
  app/src/main/AndroidManifest.xml
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/tool/DesignToolActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/adapter/HorizonAdapter.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/fragment/home_fragment.kt
  app/src/main/res/drawable/ic_baseline_add_photo_alternate_24.xml
  app/src/main/res/drawable/ic_baseline_brush_24.xml
  app/src/main/res/drawable/ic_baseline_color_lens_24.xml
  app/src/main/res/drawable/ic_baseline_photo_size_select_small_24.xml
  app/src/main/res/drawable/ic_baseline_text_fields_24.xml
  app/src/main/res/layout/activity_design.xml
  app/src/main/res/layout/home_fragment.xml
Labels: enhancement

#21 Feature/design tool3.0
  .idea/jarRepositories.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/tool/DesignToolActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/model/CanvasView.kt
  app/src/main/res/drawable/ic_baseline_cancel_24.xml
  app/src/main/res/drawable/ic_baseline_delete_24.xml
  app/src/main/res/drawable/ic_baseline_edit_18.xml
  app/src/main/res/drawable/ic_baseline_edit_24.xml
  app/src/main/res/layout/activity_design.xml
  app/src/main/res/values/styles.xml
  build.gradle
Labels: enhancement

#23 Feature/account fragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/LoginActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/SplashActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/account/NoticeActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/account/NoticeDetailActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/account/QuestionActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/account/QuestionDetailActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/account/QuiksilverActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/activity/account/informationActivity.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/adapter/NoticeAdapter.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/adapter/QuestionAdapter.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/fragment/account_fragment.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/model/NoticeItem.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/model/QuestionItem.kt
  app/src/main/res/drawable-v24/account_background.png
  app/src/main/res/drawable-v24/btn_signin_facebook.png
  app/src/main/res/drawable-v24/btn_signin_google.png
  app/src/main/res/drawable/ic_baseline_account_circle_24.xml
  app/src/main/res/drawable/information.jpg
  app/src/main/res/layout/account_fragment.xml
  app/src/main/res/layout/account_login.xml
  app/src/main/res/layout/activity_information.xml
  app/src/main/res/layout/activity_notice.xml
  app/src/main/res/layout/activity_notice_detail.xml
  app/src/main/res/layout/activity_notice_item.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/activity_question_detail.xml
  app/src/main/res/layout/activity_question_item.xml
  app/src/main/res/layout/activity_quiksilver.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: documentation, enhancement

#24 Feature/search engine
  app/build.gradle
  app/src/main/java/h2mud2/ganpanproject/gandan/adapter/SearchAdapter.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/fragment/search_fragment.kt
  app/src/main/java/h2mud2/ganpanproject/gandan/model/Item.kt
  app/src/main/res/drawable/ic_baseline_arrow_back_ios_24.xml
  app/src/main/res/layout/recycler_searchitems.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/values/array.xml
  build.gradle
Labels: bug, documentation, enhancement
